# 🔢 NumPy — Numerical Python

NumPy is the core library for numerical computing in Python.

It provides:

✅ Fast arrays and matrix operations  
✅ Math functions for stats, algebra, and calculus  
✅ Broadcasting and vectorization (no need for loops)

To install:
```bash
pip install numpy

In [1]:
import numpy as np

✅ Creating Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)  # 1D array
print(b)  # 2D array

[1 2 3]
[[1 2]
 [3 4]]


✅ Array Properties

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print("Shape:", b.shape)
print("Size:", b.size)
print("Dimensions:", b.ndim)

Shape: (2, 2)
Size: 4
Dimensions: 2


✅ Useful Array Functions

In [ ]:
np.zeros((2, 3))        # 2x3 matrix of 0s
np.ones((3, 2))         # 3x2 matrix of 1s
np.eye(3)               # Identity matrix
np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)    # 5 values between 0 and 1

✅ Indexing and Slicing

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])   # 2
print(arr[:, 1])   # [2, 5]
print(arr[1])      # [4, 5, 6]


2
[2 5]
[4 5 6]


✅ Math Operations

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)
print(np.dot(a, b))  # Dot product


[5 7 9]
[ 4 10 18]
[1 4 9]
32


✅ Boolean Masking

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40])
mask = arr > 25
print(arr[mask])  # [30 40]

[30 40]


In [16]:
import numpy as np

arr = np.arange(1,10).reshape(3,3)
print("Normal matrix", arr)
arr[arr % 2 == 0] = 0
print("Evens with zero:\n", arr)
print("Shape:", arr.shape)
print("Sum:", arr.sum())
print("Transpose:\n", arr.T)



Normal matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Evens with zero:
 [[1 0 3]
 [0 5 0]
 [7 0 9]]
Shape: (3, 3)
Sum: 25
Transpose:
 [[1 0 7]
 [0 5 0]
 [3 0 9]]
